---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ansible-postgres-docker
    image: geerlingguy/docker-ubuntu1804-ansible
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  options:
    v: false
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
