---
- name: Prepare
  hosts: all
  become: true
  vars:
    pip_install_packages:
      - name: docker
    docker_networks:
      - name: moleculenetwork
  roles:
    - calvinbui.ansible_docker
    - calvinbui.ansible_pip
    - calvinbui.ansible_docker_network
