---
- name: Prepare
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    pip_install_packages:
      - name: docker
        executable: pip3
    docker_networks:
      - name: moleculenetwork
  roles:
    - calvinbui.ansible_docker
    - calvinbui.ansible_pip
    - calvinbui.ansible_docker_network
